project:
  type: website
  output-dir: docs

website:
  title: "RPAD 500 - Foundations of Public Administration"
  navbar:
    background: danger
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus500.qmd
      - text: "Assignments"
        file: assignments.qmd
        
  sidebar: 
    - title: "Syllabus"
      style: docked
      search: true
      contents: 
        - syllabus.qmd
        
    - title: "Assignments"
      contents: 
        - assignments.qmd
        - groupassignment1.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

