project:
  type: website
  output-dir: docs

website:
  title: "RPAD 500 - Foundations of Public Administration"
  navbar:
    background: danger
    left:
      - text: "About"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus500.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

