---
title: "Group Assignment 2"
---

For assignment 2, we return to Hopetopia. All 10 groups will be representing different Hopetopia city government agencies. The assignment this time is straight forward. Each group will prepare: 1) a mission statement of no more than four sentences that captures the mission and vision of their programs; 2) a performance indicator for 3 programs; and 3) how frequently data on the performance indicator will be collected, how it will be collected and stored, and any staff that will be allocated to tracking the information (can be a full-time position, a part-time position, multiple positions, or a percentage of time of a staff with other duties). As with assignment 1, you will be writing a 1-2 page memo as a group and posting it in the Hopetopia Forum as a reply to the "Assignment 2 Thread" I have created. The memo for assignment 2 is due by midnight on Sunday, October 2nd.

The Mayor's priorities (from assignment 1) has been added to this assignment and the budget for each agency has been updated to reflect the mayor's budget guidance.

### Group Assignments

| Group   | Role                        |
|---------|-----------------------------|
| Group 4 | Police Department           |
| Group 6 | Fire Department             |
| Group 5 | Housing and Planning Agency |
| Group 1 | Buildings and Regulations   |
| Group 7 | Adult Human Services        |
| Group 2 | Youth Social Services       |
| Group 3 | Transportation Department   |
| Group 8 | General Services Department |

### Mayor's Budget Memo

Current Budget: \$5,031,509,700.00

Department of Emergency Services

-   Allocation: \$1,229,355,000

-   Rationale: Emergency Services has adequately served all four wards in Hopetopia and received 26% of the 2032 FY budget. The Mayor's Office will reassess funding increases for FY 2024.

Department of Community Development

-   Allocation: \$241,181,280

-   Rationale: Due to a lack of business development, inequitable food access, and a growing amount of inadequate housing infrastructure in the Southwest Ward, the Mayor's Office has chosen to allocate a 3% increase in the FY23 budget to the Department of Community Development. By prioritizing community development, it is our goal to create more structure and unity for everyone.

Department of Social Services

-   Allocation: \$608,625,140

-   Rationale: The betterment of a community will never be achieved without help. Due to the local supermarket closing and businesses shutting down, an increase in funding will allow the provision of expanded services. Social services can support the community with food insecurity through issuing EBT/ SNAP benefits, which will help alleviate some of the financial burden with groceries. The Mayor's Office has decided to give Social Service a 1% increase because they will help the betterment of the community, in terms of short-term goals.

Department of General Services

-   Allocation: \$974,510,280

-   Rationale: Community development is impossible without adequate transportation for all citizens in all wards of Hopetopia on safely maintained roads, bridges, and sidewalks. We have chosen to allocate a 2% increase to General Services to ensure transportation to grocery stores, social services offices, and for the maintenance of all roads in Hopetopia.

Department of Education

-   Allocation: \$1,977,838,000

-   Rationale: The Department of Education was allocated over 40% of the FY22 budget. This will be maintained for FY 23 as we want to use the surplus to address more dire needs such as food, housing, and vocational insecurities. We hope to increase economic equity throughout the wards through helping to meet more immediate needs of its citizens.
