---
title: "Group Assignment 1"
---

## Group Assignment 1
For assignment 1, 9 groups will be representing different Hopetopia city government departments and 1 group will be representing the executive branch of the city government (the mayor’s office). Fortunately, the city finds itself with a 5% budgetary surplus entering FY22 due to an uptick in economic growth in Hopetopia. The assignment will unfold in three stages:

### Stage 1 - Mayor's Office
The group representing the mayor’s office (see the table below) will kick things off. As you will see on the [City of Hopetopia website](https://stevebholt.github.io/hopetopia/mayor.html#the-mayors-budget), the city operates five city agencies - each with two departments - and the Mayor's office (you) are currently preparing your FY23 budget. Write and post a 1-page (MAXIMUM) memo to the discussion board that outlines the distribution of new funding across each agency (i.e., the total amount of money each agency may add to its budget). In the memo, the mayor’s office should offer a clear rationale for the distribution of funds and any general priorities that agencies should consider when making cuts. Of course, the mayor does not want to run afoul of voters, so the mayor’s office wants a plan from the agencies on how they will spend the dollars allocated to the agency. The memo outlining the plan for the budget is due by midnight on **Wednesday, 9/20.**

::: callout-note
The mayor’s office should post this as a new thread with the title “Budget Changes Memo” in the forum “Hopetopia - Assignment 1 Forum.” To ensure you follow the length limits and ease coordinating with groupmates, I suggest using Google Docs to write the memo and one person from the group can simply copy and paste it into the body of the thread when you are done. Be sure the post includes the names of all group members. You can either copy and paste a table with the new budget or include bullets with each agency's allocation.
:::

::: callout-tip
## Tip on Mayor's Office
The Mayor's office should think of themselves as stearing a mid-sized ship. This is a big city with a government proportionate to its size and complexity - the mayor cannot afford to be watching every line item. That's why they appoint agency heads they trust! A way to approach this is to take some time to get to know the city and its agencies, then decide - as a group - on your priorities. From there, in a Google Sheets or the Google Doc where you draft your memo, allocate the dollars available as desired across departments. Use last year's budget as a guidepost and distribute increases and decreases from there.
:::

### Stage 2 - Agency Groups
Each agency should respond to the mayor’s memo with a plan that:

  1. Examines the overall agency allocation and prepare a budget proposal that makes use of the available funds.
  2. Identifies 3 stakeholders the agency will engage to gauge priorities among key stakeholders.
  3. Outline a process for getting information from stakeholders regarding priorities. Include details like a timeline for public engagement, number of meetings with different stakeholders, schedule of meetings, and any deliverables you expect from engagement. 

The agency should include a brief rationale for the stakeholders included and the approach taken for engagement and gauging priorities. The response should be no longer than a single page. The stakeholder engagement plan is due by midnight on **Sunday, 9/24.**

::: callout-note
You will notice that most of your departments will be splitting a pool of funds allocated to your agency by the mayor's office. In addition to preparing your overall budget request, you should make the case for how much of the overall pool of new funds (or cuts) coming to the agency your department should receive and what you would plan to do with the funds (or cuts) (and the affected stakeholders) in your budget proposal memo.
:::

::: callout-tip
Use some creativity when thinking about the city of Hopetopia and the kinds of stakeholders likely to be operating in a city of that size and type. I have provided some details that you may draw on, but you should also be a little creative. I suggest using a Google Doc to draft your one page memo together and then copying and pasting the memo as a reply to the Mayor's Budget Changes Memo in the Hopetopia Assignment 1 forum.
:::

### Group Assignments

| Group  | Role |
| ------ | -------|
| Group 1 | Mayor |
| Group 2 | Police Department |
| Group 3 | Fire Department |
| Group 4 | Housing and Planning Agency |
| Group 5 | Buildings and Regulations |
| Group 6 | Adult Human Services |
| Group 7 | Youth Social Services |
| Group 8 | Transportation Department |
